#lang pollen

◊heading{Литература}

◊ol{
◊li{Добровольная лесная сертификация: учеб. пос. для вузов / А.В. Птичников, Е.В. Бубко, А.Т. Загидуллина и др.; под общ. ред. А.В. Птичникова, С.В. Третьякова, Н.М. Шматкова. Всемирный фонд дикой природы (WWF России). М., 2011. 175[1] с.}
◊li{Добровольные руководящие принципы национального мониторинга лесов. Продовольственная и сельскохозяйственная организация Объединенных Наций. Рим, 2017. ◊hyperlink["http://www.fao.org/3/a-i6767r.pdf"]{http://www.fao.org/3/a-i6767r.pdf}}
◊li{Как лесная сертификация может защитить наши леса. ◊hyperlink["https://bahna.land/ru/lesa/kak-lesnaya-sertifikatsiya-mozhet-zashchitit-nashi-lesa"]{https://bahna.land/ru/lesa/kak-lesnaya-sertifikatsiya-mozhet-zashchitit-nashi-lesa}}
◊li{Красная книга Республики Беларусь. Животные: редкие и находящиеся под угрозой исчезновения виды диких животных / Министерство природных ресурсов и охраны окружающей среды Республики Беларусь; Национальная академия наук Беларуси, пред. редкол. И.М. Качановский. 4-е изд. Минск: Беларуская энцыклапедыя iмя Петруся Броўкi, 2015. 317 с.}
◊li{Красная книга Республики Беларусь: редкие и находящиеся под угрозой исчезновения виды дикорастущих растений растения / гл. редкол.: И.М. Качановский (предс.), М.Е. Никифоров, В.И. Парфенов [и др.]. 4-е изд. Минск: Беларуская энцыклапедыя iмя Петруся Броўкi. 2015. 448 с. }
◊li{Лесной кодекс Республики Беларусь. 24 декабря 2015 г. № 332-З. Изменения и дополнения: Закон Республики Беларусь от 18 декабря 2018 г. № 152-З (Национальный правовой интернет-портал Республики Беларусь, 28.12.2018 г., 2/2590) <H11800152> ◊hyperlink["https://gosinspekciya.gov.by/actual/lesopolzovanie-i-zashchita-lesa/352/"]{https://gosinspekciya.gov.by/actual/lesopolzovanie-i-zashchita-lesa/352/}}
◊li{Практика охраны природы: практическое руководство для хранителей / сост. А.В. Абрамчук. Брест: Альтернатива, 2016. 152 с.}
◊li{Практическое руководство по выделению лесов высокой природоохранной ценности в России / Всемирный фонд природы (WWF). М., 2008. 136 c.}
◊li{Принципы лесоводства. Не имеющее обязательной силы заявление с изложением принципов для глобального консенсуса в отношении рационального использования, сохранения и устойчивого развития всех видов лесов. Приняты Конференцией ООН по окружающей среде и развитию, Рио-де-Жанейро, 14 июня 1992 года. ◊hyperlink["https://www.un.org/ru/documents/decl_conv/conventions/forest.shtml"]{https://www.un.org/ru/documents/decl_conv/conventions/forest.shtml}}
◊li{Продолжается работа над национальным стандартом лесоуправления FSC. Беларусская лесная газета. Автор: Евгений Жибуль. Дата публикации: 14.11.2019 г. ◊hyperlink["http://lesgazeta.by/news/perspektiva/prodolzhaetsja-rabota-nad-nacionalnym-standartom-lesoupravlenija-fsc"]{http://lesgazeta.by/news/perspektiva/prodolzhaetsja-rabota-nad-nacionalnym-standartom-lesoupravlenija-fsc}}
◊li{Редкие биотопы Беларуси / А.В. Пугачевский [и др.]. Минск, Альтиора: Живые краски, 2013. 236 с.}
◊li{Руководство по подготовке к добровольной лесной сертификации в Беларуси / М.В. Ермохин [и др.]. Минск, 2016. 132 с. }
◊li{Сертификация FSC Практическое пособие для местного населения. Елена Бубко, Антонина Кулясова, Татьяна Яницкая. Forest Stewardship Council®, ◊hyperlink["https://ru.fsc.org"]{ru.fsc.org}}
◊li{ТКП 17.07-01-2014 (02120) «Охрана окружающей среды и природопользование. Животный мир. Правила охраны диких животных, относящихся к видам, включенным в Красную книгу Республики Беларусь, и мест их обитания»}
◊li{ТКП 17.05-01-2014 (02120) «Охрана окружающей среды и природопользование. Растительный мир. Правила охраны дикорастущих растений, относящихся к видам, включенным в Красную книгу Республики Беларусь, и мест их произрастания»}
◊li{ТКП 17.12-06-2014 (02120) «Охрана окружающей среды и природопользование. Территории. Растительный мир. Правила выделения и охраны типичных и редких биотопов, типичных и редких ландшафтов»}
◊li{Участие общественности в принятии стратегических решений по вопросам охраны окружающей среды. Пособие для экологических общественных организаций. Подготовлено Светланой Кравченко. Европейский ЭКО-Форум, 2003. ◊hyperlink["https://www.unece.org/fileadmin/DAM/env/eia/documents/SEAguides/EcoForum%20-%20PP%20in%20Strategic%20Decisions%20-%20pamphlet%2012.1%20-%20Russian.pdf"]{https://www.unece.org/fileadmin/DAM/env/eia/docu-ments/SEAguides/EcoForum%20-%20PP%20in%20Strategic%20Decisions%20-%20pamphlet%2012.1%20-%20Russian.pdf}}
◊li{Arnstein, Sherry R. A Ladder of Citizen Participation, JAIP, Vol. 35, N 4, July 1969, p. 216-224 (Арнштейн Ш. Лестница гражданского участия. Журнал Американского института градостроителей, том 35, № 4, июль 1969, с. 216-224). Перевод на русский язык: ◊hyperlink["https://lithgow-schmidt.dk/sherry-arnstein/ru/ladder-of-citizen-participation_ru.html"]{https://lithgow-schmidt.dk/sherry-arnstein/ru/ladder-of-citizen-participation_ru.html}}
◊li{A Forest Partnership for Change WWF and IKEA Forest Programme Overview, October 2018. ◊hyperlink["https://wwwwwfse.cdn.triggerfish.cloud/uploads/2019/01/wwf-ikea-forest-partnership-for-change-2018-18-4059.pdf"]{https://wwwwwfse.cdn.triggerfish.cloud/uploads/2019/01/wwf-ikea-forest-partnership-for-change-2018-18-4059.pdf}}
◊li{Beckley, T., Parkins, J. and Sheppard, S. 2005. Public Participation in Sustainable Forest Management: A Reference Guide. Sustainable Forest Management Network, Edmonton, Alberta. 55 p. ◊hyperlink["https://cfs.nrcan.gc.ca/pubwarehouse/pdfs/26206.pdf"]{https://cfs.nrcan.gc.ca/pubwarehouse/pdfs/26206.pdf}}
◊li{Public Participation in Forestry in Europe and North America. Report of the Team of Specialists on Participation in Forestry Sectoral Activities Department. International Labour Office, Geneva. ◊hyperlink["http://www.unece.org/fileadmin/DAM/timber/joint-committee/participation/report-participation.pdf"]{http://www.unece.org/fileadmin/DAM/timber/joint-committee/participation/report-participation.pdf}}
◊li{Unifying Concepts in Ecology: Report of the plenary sessions of the First international congress of ecology, The Hague, the Netherlands, September 8–14, 1974. ◊hyperlink["https://www.researchgate.net/publication/321599251_Unifying_Concepts_in_Ecology_Report_of_the_plenary_sessions_of_the_First_international_congress_of_ecology_The_Hague_the_Netherlands_September_8-14_1974"]{https://www.researchgate.net/publication/321599251_Unifying_Concepts_in_Ecology_Report_of_the_plenary_sessions_of_the_First_international_congress_of_ecology_The_Hague_the_Netherlands_September_8-14_1974}}
◊li{World Bank. 2003. World Development Report 2004: Making services work for poor people. Overview (English). World Development Report. Washington, DC: World Bank Group. ◊hyperlink["http://documents.worldbank.org/curated/en/527371468166770790/World-Development-Report-2004-Making-services-work-for-poor-people-Overview"]{http://documents.worldbank.org/curated/en/5273-71468166770790/World-Development-Report-2004-Making-services-work-for-poor-people-Overview}}
◊li{WWF’s Living Forests Report. WWF, 2015. ◊hyperlink["https://wwf.panda.org/our_work/forests/forest_publications_news_and_reports/living_forests_report/"]{https://wwf.panda.org/our_work/forests/forest_publications_news_and_reports/living_forests_report/}}
}