book:
	raco pollen reset; raco pollen render book.ltx; raco pollen render book.pdf

site:
	raco pollen reset; raco pollen render index.html; raco pollen render -t html *.poly.pm

export:
	raco pollen publish . ../docs
